@MinimalApiPractice_HostAddress = http://localhost:5296

GET {{MinimalApiPractice_HostAddress}}/to-do-task/get-by-id/7
Accept: application/json

###

GET {{MinimalApiPractice_HostAddress}}/to-do-task/get-list
Accept: application/json

###

POST {{MinimalApiPractice_HostAddress}}/to-do-task/
Accept: application/json
Content-Type: application/json

{
  "id":6,
  "description": "the description of task 6"
}

###
